[package]
name = "concatenate-address-filter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quilkin = "0.1.0"
tokio = { version = "1", features = ["full"]}
serde = "1.0"
serde_yaml = "0.8"